load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "db",
    srcs = [
        "db.go",
        "helpers.go",
        "migrate.go",
        "models.go",
        "queries.sql.go",
    ],
    embedsrcs = [
        "migrations/000001_init.down.sql",
        "migrations/000001_init.up.sql",
    ],
    importpath = "codebase.bid/projects/yago/internal/db",
    visibility = ["//projects/yago:__subpackages__"],
    deps = [
        "//lib/go/dbmigrate",
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//pgconn",
        "@com_github_jackc_pgx_v5//pgtype",
        "@com_github_oklog_ulid_v2//:ulid",
    ],
)

go_test(
    name = "db_test",
    srcs = [
        "migrate_test.go",
        "queries_test.go",
    ],
    embed = [":db"],
    tags = [
        "local",
        "no-sandbox",
        "requires-docker",
        "requires-network",
    ],
    deps = [
        "//lib/go/testdb",
        "@com_github_jackc_pgx_v5//pgtype",
    ],
    size="small",
)
