// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PermissionAssignment struct {
	ID         int64
	RoleID     int64
	Permission string
}

type Profile struct {
	ID          int64
	Ulid        string
	OwnerID     int64
	Username    string
	DisplayName pgtype.Text
}

type Role struct {
	ID   int64
	Name string
}

type RoleAssignment struct {
	ID     int64
	UserID int64
	RoleID int64
}

type User struct {
	ID           int64
	Ulid         string
	EmailAddress string
	PasswordHash string
}
