// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}
