load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cache",
    srcs = [
        "db.go",
        "helpers.go",
        "migrate.go",
        "models.go",
        "queries.sql.go",
    ],
    embedsrcs = [
        "migrations/000001_init.down.sql",
        "migrations/000001_init.up.sql",
    ],
    importpath = "github.com/piperswe/Codebase/lib/go/cache",
    visibility = ["//visibility:public"],
    deps = ["//lib/go/dbmigrate"],
)

go_test(
    name = "cache_test",
    srcs = [
        "cache_test.go",
        "migrate_test.go",
    ],
    embed = [":cache"],
    deps = ["@org_modernc_sqlite//:sqlite"],
)
