load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "vitest",
    srcs = ["vitest.go"],
    importpath = "codeberg.org/pmc/Codebase/tools/gazelle/vitest",
    visibility = ["//visibility:public"],
    deps = [
        "@gazelle//language",
        "@gazelle//rule",
    ],
)

go_test(
    name = "vitest_test",
    srcs = ["vitest_test.go"],
    embed = [":vitest"],
    deps = [
        "@gazelle//language",
        "@gazelle//rule",
    ],
)

exports_files(["defs.bzl"])
