load("@aspect_rules_ts//ts:defs.bzl", "ts_config")
load("@gazelle//:def.bzl", "DEFAULT_LANGUAGES", "gazelle", "gazelle_binary", "gazelle_test")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@rules_oci//oci:defs.bzl", "oci_push")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

gazelle_binary(
    name = "gazelle_bin",
    languages = DEFAULT_LANGUAGES + [
        "@gazelle_cc//language/cc",
        "@contrib_rules_jvm//java/gazelle",
        "@aspect_gazelle_js",
        "//tools/gazelle/wrangler",
        "//tools/gazelle/vitest",
    ],
)

# gazelle:js_project_naming_convention {dirname}_js
# gazelle:js_tests_naming_convention {dirname}_js_tests
# gazelle:map_kind ts_project ts_project //tools/typescript:defs.bzl
gazelle(
    name = "gazelle",
    gazelle = ":gazelle_bin",
)

gazelle_test(
    name = "gazelle_test",
    workspace = "//:BUILD.bazel",
)

npm_link_all_packages(name = "node_modules")

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = [":__subpackages__"],
)

filegroup(
    name = "packages",
    srcs = [
        "//projects/datasite/cmd/datasite:datasite_packages",
        "//projects/hello_world/hello_cpp:hello_cpp_packages",
        "//projects/hello_world/hello_go:hello_go_packages",
        "//projects/hello_world/hello_java:hello_java_packages",
        "//projects/hello_world/hello_rs:hello_rs_packages",
        "//projects/hello_world/hello_ts:hello_ts_packages",
        "//projects/yago/cmd/yago:yago_packages",
    ],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "package_install_tests",
    tests = [
        "//projects/datasite/cmd/datasite:datasite_install_tests",
        "//projects/hello_world/hello_cpp:hello_cpp_install_tests",
        "//projects/hello_world/hello_go:hello_go_install_tests",
        "//projects/hello_world/hello_java:hello_java_install_tests",
        "//projects/hello_world/hello_rs:hello_rs_install_tests",
        "//projects/hello_world/hello_ts:hello_ts_install_tests",
        "//projects/yago/cmd/yago:yago_install_tests",
    ],
    visibility = ["//visibility:public"],
)

_OCI_IMAGES = [
    ("datasite", "//projects/datasite/cmd/datasite:datasite_image"),
    ("hello-cpp", "//projects/hello_world/hello_cpp:hello_cpp_image"),
    ("hello-go", "//projects/hello_world/hello_go:hello_go_image"),
    ("hello-java", "//projects/hello_world/hello_java:hello_java_image"),
    ("hello-rs", "//projects/hello_world/hello_rs:hello_rs_image"),
    ("hello-ts", "//projects/hello_world/hello_ts:hello_ts_image"),
    ("yago", "//projects/yago/cmd/yago:yago_image"),
]

[
    oci_push(
        name = "push_{}_image".format(repository.replace("-", "_")),
        image = image,
        remote_tags = ["latest"],
    )
    for repository, image in _OCI_IMAGES
]

sh_binary(
    name = "push_images",
    srcs = ["push_images.sh"],
    args = [
        "$(location :push_{}_image)={}".format(
            repository.replace("-", "_"),
            repository,
        )
        for repository, _ in _OCI_IMAGES
    ],
    data = [
        ":push_{}_image".format(repository.replace("-", "_"))
        for repository, _ in _OCI_IMAGES
    ],
)
