load("@aspect_rules_ts//ts:defs.bzl", "ts_config")
load("@gazelle//:def.bzl", "DEFAULT_LANGUAGES", "gazelle", "gazelle_binary", "gazelle_test")
load("@npm//:defs.bzl", "npm_link_all_packages")
load("@npm//:tsconfig-to-swcconfig/package_json.bzl", tsconfig_to_swcconfig = "bin")

gazelle_binary(
    name = "gazelle_bin",
    languages = DEFAULT_LANGUAGES + [
        "@gazelle_cc//language/cc",
        "@contrib_rules_jvm//java/gazelle",
        "@aspect_gazelle_js",
        "//tools/gazelle/vitest",
    ],
)

# gazelle:js_project_naming_convention {dirname}_js
# gazelle:js_tests_naming_convention {dirname}_js_tests
gazelle(
    name = "gazelle",
    gazelle = ":gazelle_bin",
)

gazelle_test(
    name = "gazelle_test",
    workspace = "//:BUILD.bazel",
)

npm_link_all_packages(name = "node_modules")

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = [":__subpackages__"],
)

tsconfig_to_swcconfig.t2s(
    name = "write_swcrc",
    srcs = ["tsconfig.json"],
    args = [
        "--filename",
        "$(location tsconfig.json)",
    ],
    stdout = ".swcrc",
    visibility = ["//:__subpackages__"],
)

filegroup(
    name = "packages",
    srcs = [
        "//projects/datasite/cmd/datasite:datasite_packages",
        "//projects/hello_world/hello_cpp:hello_cpp_packages",
        "//projects/hello_world/hello_go:hello_go_packages",
        "//projects/hello_world/hello_java:hello_java_packages",
        "//projects/hello_world/hello_rs:hello_rs_packages",
        "//projects/hello_world/hello_ts:hello_ts_packages",
    ],
    visibility = ["//visibility:public"],
)

test_suite(
    name = "package_install_tests",
    tests = [
        "//projects/datasite/cmd/datasite:datasite_install_tests",
        "//projects/hello_world/hello_cpp:hello_cpp_install_tests",
        "//projects/hello_world/hello_go:hello_go_install_tests",
        "//projects/hello_world/hello_java:hello_java_install_tests",
        "//projects/hello_world/hello_rs:hello_rs_install_tests",
        "//projects/hello_world/hello_ts:hello_ts_install_tests",
    ],
    visibility = ["//visibility:public"],
)
