[tools]
bazel = "9.2.0"
buildifier = "latest"
go = "latest"
node = "latest"
pnpm = "latest"

[env]
_.path = "./scripts"

[tasks.gazelle]
description = "Re-calculate dependencies automatically with Gazelle"
run = "bazel run //:gazelle"

[tasks.refresh]
description = "Update lockfiles for dependencies"
run = "go mod tidy && pnpm install && REPIN=1 bazel run @maven//:pin && mise gazelle && bazel mod tidy"

[tasks.build]
description = "Build everything"
run = "bazel build //..."

[tasks.test]
description = "Test everything"
run = "bazel test //..."

[tasks.setup-vscode]
description = "Setup rust-analyzer in VSCode"
run = "bazel run @rules_rust//tools/rust_analyzer:setup -- vscode"

[tasks.lint]
description = "Lint the codebase"
run = "npx oxlint"

[tasks.format]
description = "Format the codebase"
run = "npx oxfmt"

[tasks.gencode]
description = "Run `go generate` & `sqlc generate`"
run = "bazel run @com_github_sqlc_dev_sqlc//cmd/sqlc -- generate && go generate ./... && mise gazelle"

[tasks.deploy]
description = "Deploy everything"
run = "bazel run //projects/bazel_cache:deploy"