bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "platforms", version = "1.1.0")
bazel_dep(name = "aspect_rules_js", version = "3.4.0")
bazel_dep(name = "bazel_lib", version = "3.7.0")

# Translate the pnpm-lock.yaml file to bazel targets
npm = use_extension("@aspect_rules_js//npm:extensions.bzl", "npm")
npm.npm_translate_lock(
    name = "npm",
    pnpm_lock = "//:pnpm-lock.yaml",
    verify_node_modules_ignored = "//:.bazelignore",
)
use_repo(npm, "npm")

# Allows developers to use the matching pnpm version, for example:
# bazel run -- @pnpm --dir /home/runner/work/rules_js/rules_js install
pnpm = use_extension("@aspect_rules_js//npm:extensions.bzl", "pnpm", dev_dependency = True)
use_repo(pnpm, "pnpm")

bazel_dep(name = "aspect_rules_ts", version = "3.10.0")

typescript = use_extension("@aspect_rules_ts//ts:extensions.bzl", "typescript", dev_dependency = True)
typescript.deps(
    version_from = "//:package.json",
)
use_repo(typescript, "npm_typescript")

bazel_dep(name = "rules_go", version = "0.63.0")

go_sdk = use_extension("@rules_go//go:extensions.bzl", "go_sdk")
go_sdk.from_file(go_mod = "//:go.mod")

bazel_dep(name = "rules_rust", version = "0.73.0")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["nightly/2026-08-19"],
)
use_repo(rust, "rust_toolchains")

register_toolchains("@rust_toolchains//:all")

oxc_crates = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
oxc_crates.spec(
    default_features = False,
    features = [
        "ast_visit",
        "codegen",
        "semantic",
        "transformer",
    ],
    package = "oxc",
    version = "=0.146.0",
)
oxc_crates.spec(
    package = "oxc_resolver",
    version = "=11.23.0",
)
oxc_crates.from_specs(name = "oxc_crates")
use_repo(oxc_crates, "oxc_crates")

bazel_dep(name = "rules_cc", version = "0.2.18")
bazel_dep(name = "rules_android", version = "0.7.3")

remote_android_extensions = use_extension(
    "@rules_android//bzlmod_extensions:android_extensions.bzl",
    "remote_android_tools_extensions",
)
use_repo(remote_android_extensions, "android_tools")

android_sdk_repository_extension = use_extension("@rules_android//rules/android_sdk_repository:rule.bzl", "android_sdk_repository_extension")
use_repo(android_sdk_repository_extension, "androidsdk")

register_toolchains("@androidsdk//:sdk-toolchain", "@androidsdk//:all")

bazel_dep(name = "rules_java", version = "9.8.0")
bazel_dep(name = "contrib_rules_jvm", version = "0.34.0")
bazel_dep(name = "rules_jvm_external", version = "7.1")

maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [],
    known_contributing_modules = ["protobuf"],
    lock_file = "//:maven_install.json",
    repositories = [
        "https://repo1.maven.org/maven2",
    ],
)
use_repo(maven, "maven")

bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_shell", version = "0.6.1")
bazel_dep(name = "tar.bzl", version = "0.10.4")

register_toolchains("//platforms:native_rpmbuild_toolchain")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "distroless_base",
    digest = "sha256:f4a335ca209e1d2ee873102c17c389ad0142e3d5b21aee2817e9cc9c01d87d20",
    image = "gcr.io/distroless/base",
    platforms = [
        "linux/amd64",
        "linux/arm64/v8",
    ],
)
use_repo(
    oci,
    "distroless_base",
    "distroless_base_linux_amd64",
    "distroless_base_linux_arm64_v8",
)

oci.pull(
    name = "distroless_cc",
    digest = "sha256:ed7c407fd64eb0af9dddb9456b94cee188a40a7f53cf38c9836e1e9ae14fca02",
    image = "gcr.io/distroless/cc",
    platforms = [
        "linux/amd64",
        "linux/arm64/v8",
    ],
)
use_repo(
    oci,
    "distroless_cc",
    "distroless_cc_linux_amd64",
    "distroless_cc_linux_arm64_v8",
)

oci.pull(
    name = "distroless_java",
    digest = "sha256:34f47c4e018bf205c771ad12a1c8c06d0801a69c0a5566677f0e31f166c89793",
    image = "gcr.io/distroless/java25",
    platforms = [
        "linux/amd64",
        "linux/arm64/v8",
    ],
)
use_repo(
    oci,
    "distroless_java",
    "distroless_java_linux_amd64",
    "distroless_java_linux_arm64_v8",
)

oci.pull(
    name = "distroless_nodejs",
    digest = "sha256:2ab683b273ed12bcbce0005fa3488aa58dcdee31edf6fa6ab6a1351a9cbc6079",
    image = "gcr.io/distroless/nodejs26",
    platforms = [
        "linux/amd64",
        "linux/arm64/v8",
    ],
)
use_repo(
    oci,
    "distroless_nodejs",
    "distroless_nodejs_linux_amd64",
    "distroless_nodejs_linux_arm64_v8",
)

bazel_dep(name = "gazelle", version = "0.53.0")

go_deps = use_extension("@gazelle//:extensions.bzl", "go_deps")
go_deps.from_file(go_mod = "//:go.mod")
use_repo(go_deps, "com_github_a_h_templ", "com_github_coreos_go_systemd_v22", "com_github_cyruzin_golang_tmdb", "com_github_go_chi_chi_v5", "com_github_go_chi_httplog_v3", "com_github_go_faster_errors", "com_github_go_faster_jx", "com_github_golang_migrate_migrate_v4", "com_github_joho_godotenv", "com_github_ogen_go_ogen", "com_github_prometheus_client_golang", "com_github_riandyrn_otelchi", "com_github_sqlc_dev_sqlc", "com_github_systemd_slog_journal", "com_github_xsam_otelsql", "com_github_yuin_goldmark", "io_opentelemetry_go_otel", "io_opentelemetry_go_otel_exporters_otlp_otlptrace_otlptracehttp", "io_opentelemetry_go_otel_exporters_prometheus", "io_opentelemetry_go_otel_metric", "io_opentelemetry_go_otel_sdk", "io_opentelemetry_go_otel_sdk_metric", "io_opentelemetry_go_otel_trace", "org_golang_x_crypto", "org_modernc_sqlite")

bazel_dep(name = "gazelle_cc", version = "0.6.0")
bazel_dep(name = "aspect_gazelle_js", version = "1.1.2")
bazel_dep(name = "llvm", version = "0.8.3")

register_toolchains("@llvm//toolchain:all")
