load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "o11y",
    srcs = [
        "admin.go",
        "http.go",
        "logging.go",
        "o11y.go",
        "setup.go",
    ],
    importpath = "codebase.bid/lib/go/o11y",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_go_chi_httplog_v3//:httplog",
        "@com_github_go_faster_errors//:errors",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_prometheus_client_golang//prometheus/collectors",
        "@com_github_prometheus_client_golang//prometheus/promhttp",
        "@com_github_systemd_slog_journal//:slog-journal",
        "@io_opentelemetry_go_contrib_instrumentation_net_http_otelhttp//:otelhttp",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//propagation",
        "@io_opentelemetry_go_otel//semconv/v1.26.0:v1_26_0",
        "@io_opentelemetry_go_otel_exporters_otlp_otlptrace_otlptracehttp//:otlptracehttp",
        "@io_opentelemetry_go_otel_exporters_prometheus//:prometheus",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@io_opentelemetry_go_otel_sdk//resource",
        "@io_opentelemetry_go_otel_sdk//trace",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)

go_test(
    name = "o11y_test",
    srcs = [
        "admin_test.go",
        "exporters_test.go",
        "http_test.go",
        "logging_test.go",
        "o11y_test.go",
        "setup_errors_test.go",
        "setup_test.go",
        "test_helpers_test.go",
    ],
    embed = [":o11y"],
    deps = [
        "@com_github_go_chi_chi_v5//:chi",
        "@com_github_go_chi_httplog_v3//:httplog",
        "@com_github_prometheus_client_golang//prometheus",
        "@com_github_systemd_slog_journal//:slog-journal",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//propagation",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@io_opentelemetry_go_otel_metric//noop",
        "@io_opentelemetry_go_otel_sdk//resource",
        "@io_opentelemetry_go_otel_sdk//trace",
        "@io_opentelemetry_go_otel_sdk//trace/tracetest",
        "@io_opentelemetry_go_otel_sdk_metric//:metric",
        "@io_opentelemetry_go_otel_sdk_metric//metricdata",
        "@io_opentelemetry_go_otel_trace//:trace",
        "@io_opentelemetry_go_otel_trace//noop",
    ],
)
