load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "oas",
    srcs = [
        "generate.go",
        "oas_cfg_gen.go",
        "oas_client_gen.go",
        "oas_defaults_gen.go",
        "oas_handlers_gen.go",
        "oas_interfaces_gen.go",
        "oas_json_gen.go",
        "oas_labeler_gen.go",
        "oas_middleware_gen.go",
        "oas_operations_gen.go",
        "oas_parameters_gen.go",
        "oas_request_decoders_gen.go",
        "oas_request_encoders_gen.go",
        "oas_response_decoders_gen.go",
        "oas_response_encoders_gen.go",
        "oas_router_gen.go",
        "oas_schemas_gen.go",
        "oas_security_gen.go",
        "oas_server_gen.go",
        "oas_unimplemented_gen.go",
        "oas_validators_gen.go",
    ],
    importpath = "codeberg.org/pmc/Codebase/projects/datasite/internal/oas",
    visibility = ["//projects/datasite:__subpackages__"],
    deps = [
        "@com_github_go_faster_errors//:errors",
        "@com_github_go_faster_jx//:jx",
        "@com_github_ogen_go_ogen//conv",
        "@com_github_ogen_go_ogen//http",
        "@com_github_ogen_go_ogen//middleware",
        "@com_github_ogen_go_ogen//ogenerrors",
        "@com_github_ogen_go_ogen//otelogen",
        "@com_github_ogen_go_ogen//uri",
        "@com_github_ogen_go_ogen//validate",
        "@io_opentelemetry_go_otel//:otel",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//codes",
        "@io_opentelemetry_go_otel//semconv/v1.39.0:v1_39_0",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)
