// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/ogenerrors"
)

// SecurityHandler is handler for security parameters.
type SecurityHandler interface {
	// HandleAdminAPIKey handles admin_api_key security.
	// Admin API key passed as a Bearer token.
	HandleAdminAPIKey(ctx context.Context, operationName OperationName, t AdminAPIKey) (context.Context, error)
}

func findAuthorization(h http.Header, prefix string) (string, bool) {
	v, ok := h["Authorization"]
	if !ok {
		return "", false
	}
	for _, vv := range v {
		scheme, value, ok := strings.Cut(vv, " ")
		if !ok || !strings.EqualFold(scheme, prefix) {
			continue
		}
		return value, true
	}
	return "", false
}

// operationRolesAdminAPIKey is a private map storing roles per operation.
var operationRolesAdminAPIKey = map[string][]string{
	CreateCinemaOperation:   []string{},
	CreateMovieLogOperation: []string{},
	DeleteCinemaOperation:   []string{},
	DeleteMovieLogOperation: []string{},
	GetCinemaOperation:      []string{},
	GetMovieLogOperation:    []string{},
	ListCinemasOperation:    []string{},
	ListMovieLogsOperation:  []string{},
	PatchCinemaOperation:    []string{},
	PatchMovieLogOperation:  []string{},
	QuerySqlOperation:       []string{},
	UpdateCinemaOperation:   []string{},
	UpdateMovieLogOperation: []string{},
}

// GetRolesForAdminAPIKey returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForAdminAPIKey(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForAdminAPIKey(operation string) []string {
	roles, ok := operationRolesAdminAPIKey[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Server) securityAdminAPIKey(ctx context.Context, operationName OperationName, req *http.Request) (context.Context, bool, error) {
	var t AdminAPIKey
	token, ok := findAuthorization(req.Header, "Bearer")
	if !ok {
		return ctx, false, nil
	}
	t.Token = token
	t.Roles = operationRolesAdminAPIKey[operationName]
	rctx, err := s.sec.HandleAdminAPIKey(ctx, operationName, t)
	if errors.Is(err, ogenerrors.ErrSkipServerSecurity) {
		return nil, false, nil
	} else if err != nil {
		return nil, false, err
	}
	return rctx, true, err
}

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// AdminAPIKey provides admin_api_key security value.
	// Admin API key passed as a Bearer token.
	AdminAPIKey(ctx context.Context, operationName OperationName) (AdminAPIKey, error)
}

func (s *Client) securityAdminAPIKey(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.AdminAPIKey(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"AdminAPIKey\"")
	}
	req.Header.Set("Authorization", "Bearer "+t.Token)
	return nil
}
