// Code generated by ogen, DO NOT EDIT.
package oas

type CreateCinemaRes interface {
	createCinemaRes()
}

type CreateMovieLogRes interface {
	createMovieLogRes()
}

type DeleteCinemaRes interface {
	deleteCinemaRes()
}

type DeleteMovieLogRes interface {
	deleteMovieLogRes()
}

type GetCinemaRes interface {
	getCinemaRes()
}

type GetMovieLogRes interface {
	getMovieLogRes()
}

type ListCinemasRes interface {
	listCinemasRes()
}

type ListMovieLogsRes interface {
	listMovieLogsRes()
}

type PatchCinemaRes interface {
	patchCinemaRes()
}

type PatchMovieLogRes interface {
	patchMovieLogRes()
}

type QuerySqlRes interface {
	querySqlRes()
}

type UpdateCinemaRes interface {
	updateCinemaRes()
}

type UpdateMovieLogRes interface {
	updateMovieLogRes()
}
