// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"

	"github.com/go-faster/jx"
)

func (s *InternalErrorStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

type AdminAPIKey struct {
	Token string
	Roles []string
}

// GetToken returns the value of Token.
func (s *AdminAPIKey) GetToken() string {
	return s.Token
}

// GetRoles returns the value of Roles.
func (s *AdminAPIKey) GetRoles() []string {
	return s.Roles
}

// SetToken sets the value of Token.
func (s *AdminAPIKey) SetToken(val string) {
	s.Token = val
}

// SetRoles sets the value of Roles.
func (s *AdminAPIKey) SetRoles(val []string) {
	s.Roles = val
}

// Ref: #/components/schemas/Cinema
type Cinema struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// GetID returns the value of ID.
func (s *Cinema) GetID() int64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *Cinema) GetName() string {
	return s.Name
}

// SetID sets the value of ID.
func (s *Cinema) SetID(val int64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *Cinema) SetName(val string) {
	s.Name = val
}

func (*Cinema) createCinemaRes() {}
func (*Cinema) getCinemaRes()    {}
func (*Cinema) patchCinemaRes()  {}
func (*Cinema) updateCinemaRes() {}

// Ref: #/components/schemas/CinemaInput
type CinemaInput struct {
	Name string `json:"name"`
}

// GetName returns the value of Name.
func (s *CinemaInput) GetName() string {
	return s.Name
}

// SetName sets the value of Name.
func (s *CinemaInput) SetName(val string) {
	s.Name = val
}

// Ref: #/components/schemas/CinemaPatch
type CinemaPatch struct {
	Name OptString `json:"name"`
}

// GetName returns the value of Name.
func (s *CinemaPatch) GetName() OptString {
	return s.Name
}

// SetName sets the value of Name.
func (s *CinemaPatch) SetName(val OptString) {
	s.Name = val
}

type CreateCinemaBadRequest Error

func (*CreateCinemaBadRequest) createCinemaRes() {}

type CreateCinemaUnauthorized Error

func (*CreateCinemaUnauthorized) createCinemaRes() {}

type CreateMovieLogBadRequest Error

func (*CreateMovieLogBadRequest) createMovieLogRes() {}

type CreateMovieLogConflict Error

func (*CreateMovieLogConflict) createMovieLogRes() {}

type CreateMovieLogUnauthorized Error

func (*CreateMovieLogUnauthorized) createMovieLogRes() {}

type DeleteCinemaBadRequest Error

func (*DeleteCinemaBadRequest) deleteCinemaRes() {}

type DeleteCinemaConflict Error

func (*DeleteCinemaConflict) deleteCinemaRes() {}

// DeleteCinemaNoContent is response for DeleteCinema operation.
type DeleteCinemaNoContent struct{}

func (*DeleteCinemaNoContent) deleteCinemaRes() {}

type DeleteCinemaUnauthorized Error

func (*DeleteCinemaUnauthorized) deleteCinemaRes() {}

type DeleteMovieLogBadRequest Error

func (*DeleteMovieLogBadRequest) deleteMovieLogRes() {}

// DeleteMovieLogNoContent is response for DeleteMovieLog operation.
type DeleteMovieLogNoContent struct{}

func (*DeleteMovieLogNoContent) deleteMovieLogRes() {}

type DeleteMovieLogUnauthorized Error

func (*DeleteMovieLogUnauthorized) deleteMovieLogRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	Error string `json:"error"`
}

// GetError returns the value of Error.
func (s *Error) GetError() string {
	return s.Error
}

// SetError sets the value of Error.
func (s *Error) SetError(val string) {
	s.Error = val
}

func (*Error) listCinemasRes()   {}
func (*Error) listMovieLogsRes() {}

type GetCinemaBadRequest Error

func (*GetCinemaBadRequest) getCinemaRes() {}

type GetCinemaNotFound Error

func (*GetCinemaNotFound) getCinemaRes() {}

type GetCinemaUnauthorized Error

func (*GetCinemaUnauthorized) getCinemaRes() {}

type GetMovieLogBadRequest Error

func (*GetMovieLogBadRequest) getMovieLogRes() {}

type GetMovieLogNotFound Error

func (*GetMovieLogNotFound) getMovieLogRes() {}

type GetMovieLogUnauthorized Error

func (*GetMovieLogUnauthorized) getMovieLogRes() {}

// InternalErrorStatusCode wraps Error with StatusCode.
type InternalErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *InternalErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *InternalErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *InternalErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *InternalErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

func (*InternalErrorStatusCode) createCinemaRes()   {}
func (*InternalErrorStatusCode) createMovieLogRes() {}
func (*InternalErrorStatusCode) deleteCinemaRes()   {}
func (*InternalErrorStatusCode) deleteMovieLogRes() {}
func (*InternalErrorStatusCode) getCinemaRes()      {}
func (*InternalErrorStatusCode) getMovieLogRes()    {}
func (*InternalErrorStatusCode) listCinemasRes()    {}
func (*InternalErrorStatusCode) listMovieLogsRes()  {}
func (*InternalErrorStatusCode) patchCinemaRes()    {}
func (*InternalErrorStatusCode) patchMovieLogRes()  {}
func (*InternalErrorStatusCode) querySqlRes()       {}
func (*InternalErrorStatusCode) updateCinemaRes()   {}
func (*InternalErrorStatusCode) updateMovieLogRes() {}

type ListCinemasOKApplicationJSON []Cinema

func (*ListCinemasOKApplicationJSON) listCinemasRes() {}

type ListMovieLogsOKApplicationJSON []MovieLog

func (*ListMovieLogsOKApplicationJSON) listMovieLogsRes() {}

// Ref: #/components/schemas/MovieLog
type MovieLog struct {
	ID                     int64         `json:"id"`
	MovieID                int64         `json:"movie_id"`
	Date                   OptNilInt64   `json:"date"`
	CinemaID               OptNilInt64   `json:"cinema_id"`
	Rating                 OptNilFloat64 `json:"rating"`
	Review                 OptNilString  `json:"review"`
	ReviewContainsSpoilers bool          `json:"review_contains_spoilers"`
}

// GetID returns the value of ID.
func (s *MovieLog) GetID() int64 {
	return s.ID
}

// GetMovieID returns the value of MovieID.
func (s *MovieLog) GetMovieID() int64 {
	return s.MovieID
}

// GetDate returns the value of Date.
func (s *MovieLog) GetDate() OptNilInt64 {
	return s.Date
}

// GetCinemaID returns the value of CinemaID.
func (s *MovieLog) GetCinemaID() OptNilInt64 {
	return s.CinemaID
}

// GetRating returns the value of Rating.
func (s *MovieLog) GetRating() OptNilFloat64 {
	return s.Rating
}

// GetReview returns the value of Review.
func (s *MovieLog) GetReview() OptNilString {
	return s.Review
}

// GetReviewContainsSpoilers returns the value of ReviewContainsSpoilers.
func (s *MovieLog) GetReviewContainsSpoilers() bool {
	return s.ReviewContainsSpoilers
}

// SetID sets the value of ID.
func (s *MovieLog) SetID(val int64) {
	s.ID = val
}

// SetMovieID sets the value of MovieID.
func (s *MovieLog) SetMovieID(val int64) {
	s.MovieID = val
}

// SetDate sets the value of Date.
func (s *MovieLog) SetDate(val OptNilInt64) {
	s.Date = val
}

// SetCinemaID sets the value of CinemaID.
func (s *MovieLog) SetCinemaID(val OptNilInt64) {
	s.CinemaID = val
}

// SetRating sets the value of Rating.
func (s *MovieLog) SetRating(val OptNilFloat64) {
	s.Rating = val
}

// SetReview sets the value of Review.
func (s *MovieLog) SetReview(val OptNilString) {
	s.Review = val
}

// SetReviewContainsSpoilers sets the value of ReviewContainsSpoilers.
func (s *MovieLog) SetReviewContainsSpoilers(val bool) {
	s.ReviewContainsSpoilers = val
}

func (*MovieLog) createMovieLogRes() {}
func (*MovieLog) getMovieLogRes()    {}
func (*MovieLog) patchMovieLogRes()  {}
func (*MovieLog) updateMovieLogRes() {}

// Ref: #/components/schemas/MovieLogInput
type MovieLogInput struct {
	MovieID                int64         `json:"movie_id"`
	Date                   OptNilInt64   `json:"date"`
	CinemaID               OptNilInt64   `json:"cinema_id"`
	Rating                 OptNilFloat64 `json:"rating"`
	Review                 OptNilString  `json:"review"`
	ReviewContainsSpoilers OptBool       `json:"review_contains_spoilers"`
}

// GetMovieID returns the value of MovieID.
func (s *MovieLogInput) GetMovieID() int64 {
	return s.MovieID
}

// GetDate returns the value of Date.
func (s *MovieLogInput) GetDate() OptNilInt64 {
	return s.Date
}

// GetCinemaID returns the value of CinemaID.
func (s *MovieLogInput) GetCinemaID() OptNilInt64 {
	return s.CinemaID
}

// GetRating returns the value of Rating.
func (s *MovieLogInput) GetRating() OptNilFloat64 {
	return s.Rating
}

// GetReview returns the value of Review.
func (s *MovieLogInput) GetReview() OptNilString {
	return s.Review
}

// GetReviewContainsSpoilers returns the value of ReviewContainsSpoilers.
func (s *MovieLogInput) GetReviewContainsSpoilers() OptBool {
	return s.ReviewContainsSpoilers
}

// SetMovieID sets the value of MovieID.
func (s *MovieLogInput) SetMovieID(val int64) {
	s.MovieID = val
}

// SetDate sets the value of Date.
func (s *MovieLogInput) SetDate(val OptNilInt64) {
	s.Date = val
}

// SetCinemaID sets the value of CinemaID.
func (s *MovieLogInput) SetCinemaID(val OptNilInt64) {
	s.CinemaID = val
}

// SetRating sets the value of Rating.
func (s *MovieLogInput) SetRating(val OptNilFloat64) {
	s.Rating = val
}

// SetReview sets the value of Review.
func (s *MovieLogInput) SetReview(val OptNilString) {
	s.Review = val
}

// SetReviewContainsSpoilers sets the value of ReviewContainsSpoilers.
func (s *MovieLogInput) SetReviewContainsSpoilers(val OptBool) {
	s.ReviewContainsSpoilers = val
}

// Ref: #/components/schemas/MovieLogPatch
type MovieLogPatch struct {
	MovieID                OptInt64      `json:"movie_id"`
	Date                   OptNilInt64   `json:"date"`
	CinemaID               OptNilInt64   `json:"cinema_id"`
	Rating                 OptNilFloat64 `json:"rating"`
	Review                 OptNilString  `json:"review"`
	ReviewContainsSpoilers OptBool       `json:"review_contains_spoilers"`
}

// GetMovieID returns the value of MovieID.
func (s *MovieLogPatch) GetMovieID() OptInt64 {
	return s.MovieID
}

// GetDate returns the value of Date.
func (s *MovieLogPatch) GetDate() OptNilInt64 {
	return s.Date
}

// GetCinemaID returns the value of CinemaID.
func (s *MovieLogPatch) GetCinemaID() OptNilInt64 {
	return s.CinemaID
}

// GetRating returns the value of Rating.
func (s *MovieLogPatch) GetRating() OptNilFloat64 {
	return s.Rating
}

// GetReview returns the value of Review.
func (s *MovieLogPatch) GetReview() OptNilString {
	return s.Review
}

// GetReviewContainsSpoilers returns the value of ReviewContainsSpoilers.
func (s *MovieLogPatch) GetReviewContainsSpoilers() OptBool {
	return s.ReviewContainsSpoilers
}

// SetMovieID sets the value of MovieID.
func (s *MovieLogPatch) SetMovieID(val OptInt64) {
	s.MovieID = val
}

// SetDate sets the value of Date.
func (s *MovieLogPatch) SetDate(val OptNilInt64) {
	s.Date = val
}

// SetCinemaID sets the value of CinemaID.
func (s *MovieLogPatch) SetCinemaID(val OptNilInt64) {
	s.CinemaID = val
}

// SetRating sets the value of Rating.
func (s *MovieLogPatch) SetRating(val OptNilFloat64) {
	s.Rating = val
}

// SetReview sets the value of Review.
func (s *MovieLogPatch) SetReview(val OptNilString) {
	s.Review = val
}

// SetReviewContainsSpoilers sets the value of ReviewContainsSpoilers.
func (s *MovieLogPatch) SetReviewContainsSpoilers(val OptBool) {
	s.ReviewContainsSpoilers = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilFloat64 returns new OptNilFloat64 with value set to v.
func NewOptNilFloat64(v float64) OptNilFloat64 {
	return OptNilFloat64{
		Value: v,
		Set:   true,
	}
}

// OptNilFloat64 is optional nullable float64.
type OptNilFloat64 struct {
	Value float64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilFloat64 was set.
func (o OptNilFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilFloat64) SetTo(v float64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilFloat64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilFloat64) SetToNull() {
	o.Set = true
	o.Null = true
	var v float64
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilFloat64) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilFloat64) Get() (v float64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilInt64 returns new OptNilInt64 with value set to v.
func NewOptNilInt64(v int64) OptNilInt64 {
	return OptNilInt64{
		Value: v,
		Set:   true,
	}
}

// OptNilInt64 is optional nullable int64.
type OptNilInt64 struct {
	Value int64
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilInt64 was set.
func (o OptNilInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilInt64) SetTo(v int64) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilInt64) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilInt64) SetToNull() {
	o.Set = true
	o.Null = true
	var v int64
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilInt64) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilInt64) Get() (v int64, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptNilString returns new OptNilString with value set to v.
func NewOptNilString(v string) OptNilString {
	return OptNilString{
		Value: v,
		Set:   true,
	}
}

// OptNilString is optional nullable string.
type OptNilString struct {
	Value string
	Set   bool
	Null  bool
}

// IsSet returns true if OptNilString was set.
func (o OptNilString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptNilString) Reset() {
	var v string
	o.Value = v
	o.Set = false
	o.Null = false
}

// SetTo sets value to v.
func (o *OptNilString) SetTo(v string) {
	o.Set = true
	o.Null = false
	o.Value = v
}

// IsNull returns true if value is Null.
func (o OptNilString) IsNull() bool { return o.Null }

// SetToNull sets value to null.
func (o *OptNilString) SetToNull() {
	o.Set = true
	o.Null = true
	var v string
	o.Value = v
}

// IsEmpty returns true if the field was omitted from the payload (not Set and not Null).
func (o OptNilString) IsEmpty() bool {
	return !o.Set && !o.Null
}

// Get returns value and boolean that denotes whether value was set.
func (o OptNilString) Get() (v string, ok bool) {
	if o.Null {
		return v, false
	}
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptNilString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type PatchCinemaBadRequest Error

func (*PatchCinemaBadRequest) patchCinemaRes() {}

type PatchCinemaNotFound Error

func (*PatchCinemaNotFound) patchCinemaRes() {}

type PatchCinemaUnauthorized Error

func (*PatchCinemaUnauthorized) patchCinemaRes() {}

type PatchMovieLogBadRequest Error

func (*PatchMovieLogBadRequest) patchMovieLogRes() {}

type PatchMovieLogConflict Error

func (*PatchMovieLogConflict) patchMovieLogRes() {}

type PatchMovieLogNotFound Error

func (*PatchMovieLogNotFound) patchMovieLogRes() {}

type PatchMovieLogUnauthorized Error

func (*PatchMovieLogUnauthorized) patchMovieLogRes() {}

// Ref: #/components/schemas/QueryRequest
type QueryRequest struct {
	// SQL query to execute.
	SQL string `json:"sql"`
	// Page number (1-indexed).
	Page OptInt64 `json:"page"`
	// Number of rows per page.
	PageSize OptInt64 `json:"page_size"`
}

// GetSQL returns the value of SQL.
func (s *QueryRequest) GetSQL() string {
	return s.SQL
}

// GetPage returns the value of Page.
func (s *QueryRequest) GetPage() OptInt64 {
	return s.Page
}

// GetPageSize returns the value of PageSize.
func (s *QueryRequest) GetPageSize() OptInt64 {
	return s.PageSize
}

// SetSQL sets the value of SQL.
func (s *QueryRequest) SetSQL(val string) {
	s.SQL = val
}

// SetPage sets the value of Page.
func (s *QueryRequest) SetPage(val OptInt64) {
	s.Page = val
}

// SetPageSize sets the value of PageSize.
func (s *QueryRequest) SetPageSize(val OptInt64) {
	s.PageSize = val
}

// Ref: #/components/schemas/QueryResponse
type QueryResponse struct {
	// Array of row objects.
	Rows []QueryResponseRowsItem `json:"rows"`
	// Total number of rows.
	Total int64 `json:"total"`
	// Current page number.
	Page int64 `json:"page"`
	// Number of rows per page.
	PageSize int64 `json:"page_size"`
	// Total number of pages.
	TotalPages int64 `json:"total_pages"`
}

// GetRows returns the value of Rows.
func (s *QueryResponse) GetRows() []QueryResponseRowsItem {
	return s.Rows
}

// GetTotal returns the value of Total.
func (s *QueryResponse) GetTotal() int64 {
	return s.Total
}

// GetPage returns the value of Page.
func (s *QueryResponse) GetPage() int64 {
	return s.Page
}

// GetPageSize returns the value of PageSize.
func (s *QueryResponse) GetPageSize() int64 {
	return s.PageSize
}

// GetTotalPages returns the value of TotalPages.
func (s *QueryResponse) GetTotalPages() int64 {
	return s.TotalPages
}

// SetRows sets the value of Rows.
func (s *QueryResponse) SetRows(val []QueryResponseRowsItem) {
	s.Rows = val
}

// SetTotal sets the value of Total.
func (s *QueryResponse) SetTotal(val int64) {
	s.Total = val
}

// SetPage sets the value of Page.
func (s *QueryResponse) SetPage(val int64) {
	s.Page = val
}

// SetPageSize sets the value of PageSize.
func (s *QueryResponse) SetPageSize(val int64) {
	s.PageSize = val
}

// SetTotalPages sets the value of TotalPages.
func (s *QueryResponse) SetTotalPages(val int64) {
	s.TotalPages = val
}

func (*QueryResponse) querySqlRes() {}

type QueryResponseRowsItem map[string]jx.Raw

func (s *QueryResponseRowsItem) init() QueryResponseRowsItem {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

type QuerySqlBadRequest Error

func (*QuerySqlBadRequest) querySqlRes() {}

type QuerySqlUnauthorized Error

func (*QuerySqlUnauthorized) querySqlRes() {}

type UpdateCinemaBadRequest Error

func (*UpdateCinemaBadRequest) updateCinemaRes() {}

type UpdateCinemaNotFound Error

func (*UpdateCinemaNotFound) updateCinemaRes() {}

type UpdateCinemaUnauthorized Error

func (*UpdateCinemaUnauthorized) updateCinemaRes() {}

type UpdateMovieLogBadRequest Error

func (*UpdateMovieLogBadRequest) updateMovieLogRes() {}

type UpdateMovieLogConflict Error

func (*UpdateMovieLogConflict) updateMovieLogRes() {}

type UpdateMovieLogNotFound Error

func (*UpdateMovieLogNotFound) updateMovieLogRes() {}

type UpdateMovieLogUnauthorized Error

func (*UpdateMovieLogUnauthorized) updateMovieLogRes() {}
