// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateCinema implements createCinema operation.
	//
	// Create a cinema.
	//
	// POST /cinemas
	CreateCinema(ctx context.Context, req *CinemaInput) (CreateCinemaRes, error)
	// CreateMovieLog implements createMovieLog operation.
	//
	// Create a movie log.
	//
	// POST /movie_logs
	CreateMovieLog(ctx context.Context, req *MovieLogInput) (CreateMovieLogRes, error)
	// DeleteCinema implements deleteCinema operation.
	//
	// Delete a cinema.
	//
	// DELETE /cinemas/{id}
	DeleteCinema(ctx context.Context, params DeleteCinemaParams) (DeleteCinemaRes, error)
	// DeleteMovieLog implements deleteMovieLog operation.
	//
	// Delete a movie log.
	//
	// DELETE /movie_logs/{id}
	DeleteMovieLog(ctx context.Context, params DeleteMovieLogParams) (DeleteMovieLogRes, error)
	// GetCinema implements getCinema operation.
	//
	// Get a cinema by ID.
	//
	// GET /cinemas/{id}
	GetCinema(ctx context.Context, params GetCinemaParams) (GetCinemaRes, error)
	// GetMovieLog implements getMovieLog operation.
	//
	// Get a movie log by ID.
	//
	// GET /movie_logs/{id}
	GetMovieLog(ctx context.Context, params GetMovieLogParams) (GetMovieLogRes, error)
	// ListCinemas implements listCinemas operation.
	//
	// List all cinemas.
	//
	// GET /cinemas
	ListCinemas(ctx context.Context) (ListCinemasRes, error)
	// ListMovieLogs implements listMovieLogs operation.
	//
	// List all movie logs.
	//
	// GET /movie_logs
	ListMovieLogs(ctx context.Context) (ListMovieLogsRes, error)
	// PatchCinema implements patchCinema operation.
	//
	// Partially update a cinema.
	//
	// PATCH /cinemas/{id}
	PatchCinema(ctx context.Context, req *CinemaPatch, params PatchCinemaParams) (PatchCinemaRes, error)
	// PatchMovieLog implements patchMovieLog operation.
	//
	// Partially update a movie log.
	//
	// PATCH /movie_logs/{id}
	PatchMovieLog(ctx context.Context, req *MovieLogPatch, params PatchMovieLogParams) (PatchMovieLogRes, error)
	// QuerySql implements querySql operation.
	//
	// Execute a SQL query and return results.
	//
	// POST /admin/query
	QuerySql(ctx context.Context, req *QueryRequest) (QuerySqlRes, error)
	// UpdateCinema implements updateCinema operation.
	//
	// Replace a cinema.
	//
	// PUT /cinemas/{id}
	UpdateCinema(ctx context.Context, req *CinemaInput, params UpdateCinemaParams) (UpdateCinemaRes, error)
	// UpdateMovieLog implements updateMovieLog operation.
	//
	// Replace a movie log.
	//
	// PUT /movie_logs/{id}
	UpdateMovieLog(ctx context.Context, req *MovieLogInput, params UpdateMovieLogParams) (UpdateMovieLogRes, error)
	// NewError creates *InternalErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *InternalErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
