// Code generated by ogen, DO NOT EDIT.

package oas

// setDefaults set default value of fields.
func (s *QueryRequest) setDefaults() {
	{
		val := int64(1)
		s.Page.SetTo(val)
	}
	{
		val := int64(50)
		s.PageSize.SetTo(val)
	}
}
