// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateCinema implements createCinema operation.
//
// Create a cinema.
//
// POST /cinemas
func (UnimplementedHandler) CreateCinema(ctx context.Context, req *CinemaInput) (r CreateCinemaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateMovieLog implements createMovieLog operation.
//
// Create a movie log.
//
// POST /movie_logs
func (UnimplementedHandler) CreateMovieLog(ctx context.Context, req *MovieLogInput) (r CreateMovieLogRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCinema implements deleteCinema operation.
//
// Delete a cinema.
//
// DELETE /cinemas/{id}
func (UnimplementedHandler) DeleteCinema(ctx context.Context, params DeleteCinemaParams) (r DeleteCinemaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteMovieLog implements deleteMovieLog operation.
//
// Delete a movie log.
//
// DELETE /movie_logs/{id}
func (UnimplementedHandler) DeleteMovieLog(ctx context.Context, params DeleteMovieLogParams) (r DeleteMovieLogRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCinema implements getCinema operation.
//
// Get a cinema by ID.
//
// GET /cinemas/{id}
func (UnimplementedHandler) GetCinema(ctx context.Context, params GetCinemaParams) (r GetCinemaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetMovieLog implements getMovieLog operation.
//
// Get a movie log by ID.
//
// GET /movie_logs/{id}
func (UnimplementedHandler) GetMovieLog(ctx context.Context, params GetMovieLogParams) (r GetMovieLogRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListCinemas implements listCinemas operation.
//
// List all cinemas.
//
// GET /cinemas
func (UnimplementedHandler) ListCinemas(ctx context.Context) (r ListCinemasRes, _ error) {
	return r, ht.ErrNotImplemented
}

// ListMovieLogs implements listMovieLogs operation.
//
// List all movie logs.
//
// GET /movie_logs
func (UnimplementedHandler) ListMovieLogs(ctx context.Context) (r ListMovieLogsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchCinema implements patchCinema operation.
//
// Partially update a cinema.
//
// PATCH /cinemas/{id}
func (UnimplementedHandler) PatchCinema(ctx context.Context, req *CinemaPatch, params PatchCinemaParams) (r PatchCinemaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// PatchMovieLog implements patchMovieLog operation.
//
// Partially update a movie log.
//
// PATCH /movie_logs/{id}
func (UnimplementedHandler) PatchMovieLog(ctx context.Context, req *MovieLogPatch, params PatchMovieLogParams) (r PatchMovieLogRes, _ error) {
	return r, ht.ErrNotImplemented
}

// QuerySql implements querySql operation.
//
// Execute a SQL query and return results.
//
// POST /admin/query
func (UnimplementedHandler) QuerySql(ctx context.Context, req *QueryRequest) (r QuerySqlRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCinema implements updateCinema operation.
//
// Replace a cinema.
//
// PUT /cinemas/{id}
func (UnimplementedHandler) UpdateCinema(ctx context.Context, req *CinemaInput, params UpdateCinemaParams) (r UpdateCinemaRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateMovieLog implements updateMovieLog operation.
//
// Replace a movie log.
//
// PUT /movie_logs/{id}
func (UnimplementedHandler) UpdateMovieLog(ctx context.Context, req *MovieLogInput, params UpdateMovieLogParams) (r UpdateMovieLogRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *InternalErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *InternalErrorStatusCode) {
	r = new(InternalErrorStatusCode)
	return r
}
