// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateCinemaOperation   OperationName = "CreateCinema"
	CreateMovieLogOperation OperationName = "CreateMovieLog"
	DeleteCinemaOperation   OperationName = "DeleteCinema"
	DeleteMovieLogOperation OperationName = "DeleteMovieLog"
	GetCinemaOperation      OperationName = "GetCinema"
	GetMovieLogOperation    OperationName = "GetMovieLog"
	ListCinemasOperation    OperationName = "ListCinemas"
	ListMovieLogsOperation  OperationName = "ListMovieLogs"
	PatchCinemaOperation    OperationName = "PatchCinema"
	PatchMovieLogOperation  OperationName = "PatchMovieLog"
	QuerySqlOperation       OperationName = "QuerySql"
	UpdateCinemaOperation   OperationName = "UpdateCinema"
	UpdateMovieLogOperation OperationName = "UpdateMovieLog"
)
