load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "dbmigrate",
    srcs = ["dbmigrate.go"],
    importpath = "codebase.bid/lib/go/dbmigrate",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_golang_migrate_migrate_v4//:migrate",
        "@com_github_golang_migrate_migrate_v4//database/pgx/v5:pgx",
        "@com_github_golang_migrate_migrate_v4//database/sqlite",
        "@com_github_golang_migrate_migrate_v4//source/iofs",
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_jackc_pgx_v5//stdlib",
    ],
)
