load("@rules_java//java:defs.bzl", "java_binary", "java_library")
load("//platforms:oci.bzl", "binary_oci_image")
load("//platforms:packages.bzl", "linux_runtime_packages", "package_file")

java_library(
    name = "hello_java",
    srcs = ["Hello.java"],
    visibility = ["//:__subpackages__"],
)

java_binary(
    name = "Hello",
    main_class = "com.github.piperswe.codebase.projects.hello_world.hello_java.Hello",
    visibility = ["//visibility:public"],
    runtime_deps = [":hello_java"],
)

binary_oci_image(
    name = "hello_java_image",
    base = "distroless_java",
    binary = ":Hello_deploy.jar",
    entrypoint = [
        "java",
        "-jar",
        "/Hello_deploy.jar",
    ],
    visibility = ["//visibility:public"],
)

linux_runtime_packages(
    name = "hello_java_linux_packages",
    package_name = "hello-java",
    command = [
        "java",
        "-jar",
        "/usr/lib/hello-java/Hello_deploy.jar",
    ],
    deb_depends = ["openjdk-25-jre-headless"],
    description = "Hello world implemented in Java",
    executable_name = "hello_java",
    files = [
        package_file(
            src = ":Hello_deploy.jar",
            destination = "/usr/lib/hello-java/Hello_deploy.jar",
        ),
    ],
    install_test_command = ["/usr/bin/hello_java"],
    rpm_requires = ["java-25-openjdk-headless"],
    target_name = "hello_java",
    visibility = ["//visibility:public"],
)
