load("@rules_go//go:def.bzl", "go_binary", "go_library")
load("//platforms:binary.bzl", "platform_binary")
load("//platforms:oci.bzl", "binary_oci_image")
load("//platforms:packages.bzl", "linux_binary_packages")

go_library(
    name = "interface_lib",
    srcs = ["main.go"],
    importpath = "github.com/piperswe/Codebase/projects/interface/cmd/interface",
    visibility = ["//visibility:private"],
    deps = [
        "//projects/interface/internal/version",
        "@com_github_coreos_go_systemd_v22//daemon",
    ],
)

go_binary(
    name = "interface",
    embed = [":yago_lib"],
    visibility = ["//visibility:public"],
)

platform_binary(
    name = "interface_linux_amd64",
    binary = ":interface",
    platform = "//platforms:linux_amd64",
)

platform_binary(
    name = "interface_linux_arm64",
    binary = ":interface",
    platform = "//platforms:linux_arm64",
)

binary_oci_image(
    name = "interface_image",
    base = "distroless_base",
    binary = ":interface_linux_{arch}",
    entrypoint = ["/interface"],
    visibility = ["//visibility:public"],
)

linux_binary_packages(
    name = "interface_linux_packages",
    package_name = "interface",
    binary = ":interface_linux_{arch}",
    deb_depends = [
        "libc6",
        "systemd",
    ],
    description = "Social media website",
    executable_name = "interface",
    install_test_command = [
        "/usr/bin/interface",
        "smoke",
    ],
    rpm_requires = [
        "glibc",
        "systemd",
    ],
    target_name = "interface",
    visibility = ["//visibility:public"],
)

go_library(
    name = "yago_lib",
    srcs = ["main.go"],
    importpath = "github.com/piperswe/Codebase/projects/interface/cmd/yago",
    visibility = ["//visibility:private"],
    deps = [
        "//projects/interface/internal/version",
        "@com_github_coreos_go_systemd_v22//daemon",
    ],
)
