load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "moviedb",
    srcs = ["moviedb.go"],
    importpath = "codebase.bid/projects/datasite/internal/moviedb",
    visibility = ["//projects/datasite:__subpackages__"],
    deps = [
        "//lib/go/cache",
        "//projects/datasite/internal/metrics",
        "@com_github_cyruzin_golang_tmdb//:golang-tmdb",
        "@io_opentelemetry_go_otel//attribute",
        "@io_opentelemetry_go_otel//codes",
        "@io_opentelemetry_go_otel_metric//:metric",
        "@io_opentelemetry_go_otel_trace//:trace",
    ],
)

go_test(
    name = "moviedb_test",
    srcs = ["moviedb_test.go"],
    embed = [":moviedb"],
    deps = [
        "//lib/go/cache",
        "@com_github_cyruzin_golang_tmdb//:golang-tmdb",
        "@io_opentelemetry_go_otel_trace//noop",
        "@org_modernc_sqlite//:sqlite",
    ],
)
