load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "tool",
    srcs = ["tool.go"],
    importpath = "codeberg.org/pmc/Codebase/projects/datasite/internal/tool",
    visibility = ["//projects/datasite:__subpackages__"],
    deps = [
        "@com_github_a_h_templ//:templ",
        "@com_github_ogen_go_ogen//:ogen",
        "@com_github_sqlc_dev_sqlc//:sqlc",
    ],
)
