load("@aspect_rules_ts//ts:defs.bzl", "ts_config")
load("//tools/gazelle/wrangler:defs.bzl", "directory_path", "wrangler", "write_source_files")
load("//tools/typescript:defs.bzl", "ts_project")

ts_project(
    name = "bazel_cache_js",
    srcs = [
        "index.ts",
        "worker-configuration.d.ts",
    ],
    declaration = True,
    source_map = True,
    tsconfig = ":tsconfig",
    deps = ["//lib/ts/http:http_js"],
)

ts_config(
    name = "tsconfig",
    src = "tsconfig.json",
    visibility = [":__subpackages__"],
    deps = ["//:tsconfig"],
)

wrangler.wrangler(
    name = "generated_types",
    srcs = ["wrangler.toml"],
    args = [
        "types",
        "--config",
        "wrangler.toml",
        "types/worker-configuration.d.ts",
    ],
    chdir = package_name(),
    env = {"WRANGLER_WRITE_LOGS": "false"},
    out_dirs = ["types"],
)

write_source_files(
    name = "typegen",
    files = {
        "worker-configuration.d.ts": ":generated_types_file",
    },
)

wrangler.wrangler_binary(
    name = "deploy",
    data = [
        "wrangler.toml",
        ":bazel_cache_js",
    ],
    fixed_args = [
        "deploy",
        "--config",
        "$(rootpath wrangler.toml)",
    ],
)

directory_path(
    name = "generated_types_file",
    directory = ":generated_types",
    path = "worker-configuration.d.ts",
)
