// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const createCinema = `-- name: CreateCinema :one
INSERT INTO cinemas(name) VALUES (?) RETURNING id, name
`

func (q *Queries) CreateCinema(ctx context.Context, name string) (Cinema, error) {
	row := q.db.QueryRowContext(ctx, createCinema, name)
	var i Cinema
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteCinema = `-- name: DeleteCinema :exec
DELETE FROM cinemas WHERE id = ?
`

func (q *Queries) DeleteCinema(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCinema, id)
	return err
}

const deleteMovieLog = `-- name: DeleteMovieLog :exec
DELETE FROM movie_logs WHERE id = ?
`

func (q *Queries) DeleteMovieLog(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMovieLog, id)
	return err
}

const editMovieLog = `-- name: EditMovieLog :one
UPDATE movie_logs
    SET movie_id = ?, date = ?, cinema_id = ?, rating = ?, review = ?, review_contains_spoilers = ?
    WHERE id = ?
    RETURNING id, movie_id, date, cinema_id, rating, review, review_contains_spoilers
`

type EditMovieLogParams struct {
	MovieID                int64
	Date                   sql.NullInt64
	CinemaID               sql.NullInt64
	Rating                 sql.NullFloat64
	Review                 sql.NullString
	ReviewContainsSpoilers bool
	ID                     int64
}

func (q *Queries) EditMovieLog(ctx context.Context, arg EditMovieLogParams) (MovieLog, error) {
	row := q.db.QueryRowContext(ctx, editMovieLog,
		arg.MovieID,
		arg.Date,
		arg.CinemaID,
		arg.Rating,
		arg.Review,
		arg.ReviewContainsSpoilers,
		arg.ID,
	)
	var i MovieLog
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Date,
		&i.CinemaID,
		&i.Rating,
		&i.Review,
		&i.ReviewContainsSpoilers,
	)
	return i, err
}

const getCinema = `-- name: GetCinema :one
SELECT id, name FROM cinemas WHERE id = ?
`

func (q *Queries) GetCinema(ctx context.Context, id int64) (Cinema, error) {
	row := q.db.QueryRowContext(ctx, getCinema, id)
	var i Cinema
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getLogsForMovie = `-- name: GetLogsForMovie :many
SELECT id, movie_id, date, cinema_id, rating, review, review_contains_spoilers FROM movie_logs WHERE movie_id = ?
`

func (q *Queries) GetLogsForMovie(ctx context.Context, movieID int64) ([]MovieLog, error) {
	rows, err := q.db.QueryContext(ctx, getLogsForMovie, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieLog
	for rows.Next() {
		var i MovieLog
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Date,
			&i.CinemaID,
			&i.Rating,
			&i.Review,
			&i.ReviewContainsSpoilers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovieLog = `-- name: GetMovieLog :one
SELECT id, movie_id, date, cinema_id, rating, review, review_contains_spoilers FROM movie_logs WHERE id = ?
`

func (q *Queries) GetMovieLog(ctx context.Context, id int64) (MovieLog, error) {
	row := q.db.QueryRowContext(ctx, getMovieLog, id)
	var i MovieLog
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Date,
		&i.CinemaID,
		&i.Rating,
		&i.Review,
		&i.ReviewContainsSpoilers,
	)
	return i, err
}

const getMovieLogsForCinema = `-- name: GetMovieLogsForCinema :many
SELECT id, movie_id, date, cinema_id, rating, review, review_contains_spoilers FROM movie_logs WHERE cinema_id = ?
`

func (q *Queries) GetMovieLogsForCinema(ctx context.Context, cinemaID sql.NullInt64) ([]MovieLog, error) {
	rows, err := q.db.QueryContext(ctx, getMovieLogsForCinema, cinemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieLog
	for rows.Next() {
		var i MovieLog
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Date,
			&i.CinemaID,
			&i.Rating,
			&i.Review,
			&i.ReviewContainsSpoilers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentMovieLogs = `-- name: GetRecentMovieLogs :many
SELECT id, movie_id, date, cinema_id, rating, review, review_contains_spoilers FROM movie_logs ORDER BY date DESC LIMIT ?
`

func (q *Queries) GetRecentMovieLogs(ctx context.Context, limit int64) ([]MovieLog, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMovieLogs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieLog
	for rows.Next() {
		var i MovieLog
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Date,
			&i.CinemaID,
			&i.Rating,
			&i.Review,
			&i.ReviewContainsSpoilers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCinemas = `-- name: ListCinemas :many
SELECT id, name FROM cinemas ORDER BY name
`

func (q *Queries) ListCinemas(ctx context.Context) ([]Cinema, error) {
	rows, err := q.db.QueryContext(ctx, listCinemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Cinema
	for rows.Next() {
		var i Cinema
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMovieLogs = `-- name: ListMovieLogs :many
SELECT id, movie_id, date, cinema_id, rating, review, review_contains_spoilers FROM movie_logs ORDER BY date DESC
`

func (q *Queries) ListMovieLogs(ctx context.Context) ([]MovieLog, error) {
	rows, err := q.db.QueryContext(ctx, listMovieLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MovieLog
	for rows.Next() {
		var i MovieLog
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Date,
			&i.CinemaID,
			&i.Rating,
			&i.Review,
			&i.ReviewContainsSpoilers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logMovie = `-- name: LogMovie :one
INSERT INTO
    movie_logs(movie_id, date, cinema_id, rating, review, review_contains_spoilers)
    VALUES (?, ?, ?, ?, ?, ?)
    RETURNING id, movie_id, date, cinema_id, rating, review, review_contains_spoilers
`

type LogMovieParams struct {
	MovieID                int64
	Date                   sql.NullInt64
	CinemaID               sql.NullInt64
	Rating                 sql.NullFloat64
	Review                 sql.NullString
	ReviewContainsSpoilers bool
}

func (q *Queries) LogMovie(ctx context.Context, arg LogMovieParams) (MovieLog, error) {
	row := q.db.QueryRowContext(ctx, logMovie,
		arg.MovieID,
		arg.Date,
		arg.CinemaID,
		arg.Rating,
		arg.Review,
		arg.ReviewContainsSpoilers,
	)
	var i MovieLog
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Date,
		&i.CinemaID,
		&i.Rating,
		&i.Review,
		&i.ReviewContainsSpoilers,
	)
	return i, err
}

const updateCinema = `-- name: UpdateCinema :one
UPDATE cinemas
    SET name = ?
    WHERE id = ?
    RETURNING id, name
`

type UpdateCinemaParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateCinema(ctx context.Context, arg UpdateCinemaParams) (Cinema, error) {
	row := q.db.QueryRowContext(ctx, updateCinema, arg.Name, arg.ID)
	var i Cinema
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
