load("//tools/gazelle/vitest:defs.bzl", "vitest")
load("//tools/typescript:defs.bzl", "ts_project")

ts_project(
    name = "vector_js",
    srcs = ["vector.ts"],
    declaration = True,
    source_map = True,
    tsconfig = "//:tsconfig",
    visibility = ["//visibility:public"],
)

ts_project(
    name = "vector_js_tests",
    testonly = True,
    srcs = ["vector.test.ts"],
    declaration = True,
    source_map = True,
    tsconfig = "//:tsconfig",
    deps = [
        ":vector_js",
        "//:node_modules/vitest",
    ],
)

vitest.vitest_test(
    name = "test",
    args = ["run"],
    chdir = package_name(),
    data = [
        ":vector_js",
        ":vector_js_tests",
        "//:node_modules/vitest",
    ],
)
