load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "rbac",
    srcs = [
        "actions.go",
        "permissions.go",
        "resources.go",
    ],
    importpath = "github.com/piperswe/Codebase/projects/yago/internal/rbac",
    visibility = ["//projects/yago:__subpackages__"],
    deps = ["//projects/yago/internal/db"],
)
