load("@aspect_rules_js//js:defs.bzl", "js_binary")
load("@aspect_rules_swc//swc:defs.bzl", "swc")
load("@aspect_rules_ts//ts:defs.bzl", "ts_project")
load("@bazel_skylib//lib:partial.bzl", "partial")

ts_project(
    name = "hello_ts_js",
    srcs = ["hello.ts"],
    declaration = True,
    source_map = True,
    transpiler = partial.make(
        swc,
        swcrc = "//:.swcrc",
    ),
    tsconfig = "//:tsconfig",
    visibility = ["//visibility:public"],
    deps = [
        "//lib/ts/vector:vector_js",
    ],
)

js_binary(
    name = "hello_ts",
    data = [":hello_ts_js"],
    entry_point = "hello.js",
)
