load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "testdb",
    srcs = ["testdb.go"],
    importpath = "github.com/piperswe/Codebase/lib/go/testdb",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_jackc_pgx_v5//:pgx",
        "@com_github_testcontainers_testcontainers_go//:testcontainers-go",
        "@com_github_testcontainers_testcontainers_go//wait",
        "@com_github_testcontainers_testcontainers_go_modules_postgres//:postgres",
    ],
)
