// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package cache

import (
	"context"
)

const deleteExpired = `-- name: DeleteExpired :exec
DELETE FROM cache_items WHERE expires <= unixepoch('now')
`

func (q *Queries) DeleteExpired(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpired)
	return err
}

const lookup = `-- name: Lookup :many
SELECT "partition", cache_key, cache_value, expires FROM cache_items WHERE partition = ? AND cache_key = ? AND expires > unixepoch('now')
`

type LookupParams struct {
	Partition int64
	CacheKey  string
}

func (q *Queries) Lookup(ctx context.Context, arg LookupParams) ([]CacheItem, error) {
	rows, err := q.db.QueryContext(ctx, lookup, arg.Partition, arg.CacheKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CacheItem
	for rows.Next() {
		var i CacheItem
		if err := rows.Scan(
			&i.Partition,
			&i.CacheKey,
			&i.CacheValue,
			&i.Expires,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const write = `-- name: Write :exec
INSERT INTO cache_items(partition, cache_key, cache_value, expires) VALUES (?, ?, ?, ?)
    ON CONFLICT(partition, cache_key) DO UPDATE SET cache_value = excluded.cache_value, expires = excluded.expires
`

type WriteParams struct {
	Partition  int64
	CacheKey   string
	CacheValue []byte
	Expires    int64
}

func (q *Queries) Write(ctx context.Context, arg WriteParams) error {
	_, err := q.db.ExecContext(ctx, write,
		arg.Partition,
		arg.CacheKey,
		arg.CacheValue,
		arg.Expires,
	)
	return err
}
