load("@rules_cc//cc:defs.bzl", "cc_binary")
load("//platforms:binary.bzl", "platform_binary")
load("//platforms:oci.bzl", "binary_oci_image")
load("//platforms:packages.bzl", "linux_binary_packages")

cc_binary(
    name = "hello_cpp",
    srcs = ["hello.cpp"],
)

platform_binary(
    name = "hello_cpp_linux_amd64",
    binary = ":hello_cpp",
    platform = "//platforms:linux_amd64",
)

platform_binary(
    name = "hello_cpp_linux_arm64",
    binary = ":hello_cpp",
    platform = "//platforms:linux_arm64",
)

binary_oci_image(
    name = "hello_cpp_image",
    base = "distroless_cc",
    binary = ":hello_cpp_linux_{arch}",
    entrypoint = ["/hello_cpp"],
    visibility = ["//visibility:public"],
)

linux_binary_packages(
    name = "hello_cpp_linux_packages",
    package_name = "hello-cpp",
    binary = ":hello_cpp_linux_{arch}",
    deb_depends = [
        "libc6",
        "libstdc++6",
    ],
    description = "Hello world implemented in C++",
    executable_name = "hello_cpp",
    install_test_command = ["/usr/bin/hello_cpp"],
    rpm_requires = [
        "glibc",
        "libstdc++",
    ],
    target_name = "hello_cpp",
    visibility = ["//visibility:public"],
)
