load("@bazel_lib//lib:copy_to_directory.bzl", "copy_to_directory")
load("@bazel_lib//lib:directory_path.bzl", "directory_path")
load("@rules_go//go:def.bzl", "go_library")

directory_path(
    name = "bootstrap_dist_from_npm",
    directory = "//:node_modules/bootstrap/dir",
    path = "dist",
)

copy_to_directory(
    name = "bootstrap_dist",
    srcs = [":bootstrap_dist_from_npm"],
    out = "static",
    root_paths = ["**/bootstrap/dist"],
)

go_library(
    name = "static",
    srcs = ["static.go"],
    embedsrcs = [":bootstrap_dist"],
    importpath = "codebase.bid/projects/datasite/internal/static",
    visibility = ["//projects/datasite:__subpackages__"],
)
